title: <p align="center"> BINOJ VARGHESE </p>

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/binoj-v-7042726/">LinkedIn</a> |
  <a href="https://github.com/Binojv">GitHub</a>
  
  <br>   
  Binoj is a seasoned IT professional with 14+ years of industry experience in Client Engagement, Pre-sales,Business Development and Strategic Account Management having worked
  across Banking, Insurance, Manufacturing and Oil&Gas industries across US, Middle East, APAC and India. Technology and Fintech enthusiast with interests in Artificial
  Intelligence, Machine Learning, and Blockchain.
  <br>
  </p>

theme: jekyll-theme-minimal
