title: BINOJ VARGHESE
Description: Binoj is a seasoned IT professional with 14+ years of industry experience in Client Engagement, Pre-sales,Business Development and Strategic Account Management having worked across Banking, Insurance, Manufacturing and Oil&Gas industries across US, Middle East, APAC and India. Technology and Fintech enthusiast with interests in Artificial Intelligence, Machine Learning, and Blockchain.
theme: jekyll-theme-minimal
